version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    ports:
      - "3306:3306"

  postgres:
    image: postgres:16-alpine3.18
    container_name: postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
    ports:
      - '5432:5432'